---
- name: Playbook to configure phpipam
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../01.ipam/tf_ansible_vars_file.yaml
    - vars.yaml
    - credentials.yaml
  
  vars:
    ipam_base: "{{ipam_url}}api/{{phpipam_app_id}}/"
  
  module_defaults:
    ansible.builtin.uri:
      validate_certs: false
      headers:
          token: "{{phpipam_token}}"

  tasks:
    - name: Creating a section
      uri:
        url: "{{ipam_base}}sections/"
        method: POST
        body_format: json
        body: |-
          {
            "name": "NaC AWS",
            "description": "Network As Code in AWS",
            "showVLAN": 0,
            "showVRF": 0,
            "strictMode": 1,
            "permissions": "{\"3\":\"1\",\"2\":\"2\"}"
          }
        status_code: 201
        return_content: true
      register: result
    
    - name: Getting ID of section
      set_fact:
        section_id: "{{result.json.id}}"
    
    - name: Storing ID of section
      lineinfile:
        path: "{{artifacts_file}}"
        line: "section_id: {{section_id}}"
        create: yes

    - name: Create supernet for region 1
      uri:
        url: "{{ipam_base}}subnets/"
        method: POST
        body_format: json
        body: |-
          {
            "subnet": "{{region1_cidr.split('/').0}}",
            "mask": "{{region1_cidr.split('/').1}}",
            "description": "Region 1 supernet",
            "sectionId": {{section_id}}
          }
        status_code: 201
        return_content: true
      register: result

    - name: Getting ID of supernet 1
      set_fact:
        supernet1_id: "{{result.json.id}}"

    - name: Storing ID of supernet 1
      lineinfile:
        path: "{{artifacts_file}}"
        line: "supernet1_id: {{supernet1_id}}"

    - name: Create supernet for region 2
      uri:
        url: "{{ipam_base}}subnets/"
        method: POST
        body_format: json
        body: |-
          {
            "subnet": "{{region2_cidr.split('/').0}}",
            "mask": "{{region2_cidr.split('/').1}}",
            "description": "Region 2 supernet",
            "sectionId": {{section_id}}
          }
        status_code: 201
        return_content: true
      register: result

    - name: Getting ID of supernet 2
      set_fact:
        supernet2_id: "{{result.json.id}}"

    - name: Storing ID of supernet 2
      lineinfile:
        path: "{{artifacts_file}}"
        line: "supernet2_id: {{supernet2_id}}"

    - copy:
        dest: "{{env_file}}"
        content: "{{env | to_json}}"
      vars:
        env:
          ipam_base: "{{ipam_base}}"
          ipam_token: "{{phpipam_token}}"
          supernets:
            - id: "{{supernet1_id}}"
              cidr: "{{region1_cidr}}"
            - id: "{{supernet2_id}}"
              cidr: "{{region2_cidr}}"